//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCompany.Codex.WinApp.Services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.ICodexService")]
    public interface ICodexService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodexService/GetCreatures", ReplyAction="http://tempuri.org/ICodexService/GetCreaturesResponse")]
        MyCompany.Codex.Dtos.CreatureDto[] GetCreatures();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodexService/GetCreatures", ReplyAction="http://tempuri.org/ICodexService/GetCreaturesResponse")]
        System.Threading.Tasks.Task<MyCompany.Codex.Dtos.CreatureDto[]> GetCreaturesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICodexServiceChannel : MyCompany.Codex.WinApp.Services.ICodexService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CodexServiceClient : System.ServiceModel.ClientBase<MyCompany.Codex.WinApp.Services.ICodexService>, MyCompany.Codex.WinApp.Services.ICodexService {
        
        public CodexServiceClient() {
        }
        
        public CodexServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CodexServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodexServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodexServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MyCompany.Codex.Dtos.CreatureDto[] GetCreatures() {
            return base.Channel.GetCreatures();
        }
        
        public System.Threading.Tasks.Task<MyCompany.Codex.Dtos.CreatureDto[]> GetCreaturesAsync() {
            return base.Channel.GetCreaturesAsync();
        }
    }
}
