//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCompany.Codex.WinApp.Services {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Creature", Namespace="http://schemas.datacontract.org/2004/07/MyCompany.Codex.WebApp.Dtos")]
    [System.SerializableAttribute()]
    public partial class Creature : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.ICodexService")]
    public interface ICodexService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodexService/GetCreatures", ReplyAction="http://tempuri.org/ICodexService/GetCreaturesResponse")]
        MyCompany.Codex.WinApp.Services.Creature[] GetCreatures();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodexService/GetCreatures", ReplyAction="http://tempuri.org/ICodexService/GetCreaturesResponse")]
        System.Threading.Tasks.Task<MyCompany.Codex.WinApp.Services.Creature[]> GetCreaturesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICodexServiceChannel : MyCompany.Codex.WinApp.Services.ICodexService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CodexServiceClient : System.ServiceModel.ClientBase<MyCompany.Codex.WinApp.Services.ICodexService>, MyCompany.Codex.WinApp.Services.ICodexService {
        
        public CodexServiceClient() {
        }
        
        public CodexServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CodexServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodexServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodexServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MyCompany.Codex.WinApp.Services.Creature[] GetCreatures() {
            return base.Channel.GetCreatures();
        }
        
        public System.Threading.Tasks.Task<MyCompany.Codex.WinApp.Services.Creature[]> GetCreaturesAsync() {
            return base.Channel.GetCreaturesAsync();
        }
    }
}
